### PR TITLE
Improvement/HOLO 627 add code coverage

### PR DESCRIPTION
**Pull request by BravoNatalie**
## Describe Changes

- added package `solidity-coverage`
- added file `.solcover.js`
- added `yarn coverage`

run with:
```
HOLOGRAPH_ENVIRONMENT=experimental yarn coverage --network localhost --testfiles "test/{10,12,16}*.ts"
```

ps.: As an attempt to run 2 networks run `yarn ganache2` in one terminal and execute the coverage in another one.

```
HOLOGRAPH_ENVIRONMENT=experimental yarn coverage --network localhost
```

image

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] Code styles have been enforced
- [ ] All Hardhat tests are passing

### CODE REVIEW

**Comment by sogoiii** [comment]
@BravoNatalie since we are going to ignore experimental from now on, we can ignore that env variable value. Can you add a nice package.json script like `coverage:dev` that passes the right set of flags. And maybe add to the readme section a little bit about the coverage and why some values may seem low.

**Comment by alexanderattar** [comment]
This is looking good so far. Is the image above from the generated report. Are you also viewing the report in your terminal?

**Comment by BravoNatalie** [comment]
> This is looking good so far. Is the image above from the generated report. Are you also viewing the report in your terminal?

No, the coverage generates an HTML report.

**Review by alexanderattar — COMMENTED** [review]
This is deprecated. It never got completed and we're moving to Foundry now over a year later 🙂

**Pull request closed without merging**
